--01. TABLE_CAM
--CAM_ID Текстовый 255			pk
--CAM_NAME Текстовый 255		unique
--CAM_ADDRESS Текстовый 255
--CAM_TYPE Текстовый 255
--INSPECTED_FLAG Текстовый 255
--OVERVIEW_TYPE Текстовый 255
--RELATED_AMOUNT Длинное целое 
--SELECTION Текстовый			idx
--LAST_MODIFIED Дата/время 
--USER_LAST_CHANGE Текстовый
CREATE TABLE TABLE_CAM
(
CAM_ID VARCHAR(256) NOT NULL,
CAM_NAME VARCHAR(256) NOT NULL,
CAM_ADDRESS VARCHAR(256),
CAM_TYPE VARCHAR(256),
INSPECTED_FLAG VARCHAR(256),
OVERVIEW_TYPE VARCHAR(256),
RELATED_AMOUNT INTEGER, 
SELECTION VARCHAR(256),
LAST_MODIFIED VARCHAR(16), 
USER_LAST_CHANGE VARCHAR(256)
);
CREATE UNIQUE INDEX pk_TABLE_CAM ON TABLE_CAM (CAM_ID ASC);
CREATE UNIQUE INDEX idx_CAM_NAME ON TABLE_CAM (CAM_NAME ASC);
CREATE INDEX idx_TABLE_CAM_selection ON TABLE_CAM (SELECTION ASC);
-------------------------------------------------------------------------------

--02. TABLE_CAM_TO_OBJECT
--key Длинное целое 			pk
--CAM_ID Текстовый 255
--OBJECT_TYPE Текстовый 255		idx
--OBJECT_ID Текстовый 255
--OBJECT_NAME Текстовый 255
--OBJECT_VIEW_GRADE Целое 2
--DATE_OF_RECORD Дата/время 8
--USER_CREATED Текстовый
CREATE TABLE TABLE_CAM_TO_OBJECT
(
KEY_TABLE_CAM_TO_OBJECT INTEGER NOT NULL,
CAM_ID VARCHAR(256),
OBJECT_TYPE VARCHAR(256),
OBJECT_ID VARCHAR(256),
OBJECT_NAME VARCHAR(256),
OBJECT_VIEW_GRADE SMALLINT,
DATE_OF_RECORD VARCHAR(16), 
USER_CREATED VARCHAR(256)
);
CREATE UNIQUE INDEX pk_TABLE_CAM_TO_OBJECT ON TABLE_CAM_TO_OBJECT (KEY_TABLE_CAM_TO_OBJECT ASC);
CREATE INDEX idx_TABLE_CAM_TO_OBJECT_CAM_ID ON TABLE_CAM_TO_OBJECT (CAM_ID ASC);
CREATE INDEX idx_TABLE_CAM_TO_OBJECT_OBJECT_TYPE ON TABLE_CAM_TO_OBJECT (OBJECT_TYPE ASC);
-------------------------------------------------------------------------------

--03. TABLE_OBJECT_TYPES
--OBJECT_TYPE Текстовый 255		pk
--OBJECT_TYPE_DESCRIPTION Текстовый 255
CREATE TABLE TABLE_OBJECT_TYPES
(
OBJECT_TYPE VARCHAR(256) NOT NULL,
OBJECT_TYPE_DESCRIPTION VARCHAR(256)
);
CREATE UNIQUE INDEX pk_TABLE_OBJECT_TYPES ON TABLE_OBJECT_TYPES (OBJECT_TYPE ASC);
-------------------------------------------------------------------------------

--04. TABLE_OVERVIEW_TYPE		pk
--OVERVIEW_TYPE Текстовый 255
--OVERVIEW_TYPE_DESCRIPTION Текстовый 255
CREATE TABLE TABLE_OVERVIEW_TYPE
(
OVERVIEW_TYPE VARCHAR(256) NOT NULL,
OVERVIEW_TYPE_DESCRIPTION VARCHAR(256)
);
CREATE UNIQUE INDEX pk_TABLE_OVERVIEW_TYPE ON TABLE_OVERVIEW_TYPE (OVERVIEW_TYPE ASC);
-------------------------------------------------------------------------------

--05. TABLE_SELECTION
--SELECTION Текстовый 255
CREATE TABLE TABLE_SELECTION
(
SELECTION VARCHAR(256) NOT NULL
);
CREATE UNIQUE INDEX pk_TABLE_SELECTION ON TABLE_SELECTION (SELECTION ASC);
-------------------------------------------------------------------------------

--06. TABLE_VIOLATION
CREATE TABLE TABLE_VIOLATION
(
ID_VIOLATION INTEGER NOT NULL,
REGNUM VARCHAR(64),
VIOLATION_TYPE VARCHAR(256),
OKRUG VARCHAR(256),
PREF VARCHAR(256),
DISTRICT VARCHAR(256),
CAM_NAME VARCHAR(256),
OBJECT_TYPE VARCHAR(256),
OBJECT_ID VARCHAR(256),
OBJECT_NAME VARCHAR(256),
VIOLATION_DATE VARCHAR(32),
RECORD_DATE VARCHAR(32),
URL VARCHAR(256),
USER_CREATED VARCHAR(256),
NOTE VARCHAR(256)
);
CREATE UNIQUE INDEX pk_TABLE_VIOLATION ON TABLE_VIOLATION (ID_VIOLATION ASC);
INSERT INTO TABLE_VIOLATION (ID_VIOLATION) VALUES(0);
-------------------------------------------------------------------------------

--07. TABLE_VIOLATION_TYPE
CREATE TABLE TABLE_VIOLATION_TYPE
(
VIOLATION_TYPE VARCHAR(256) NOT NULL,
VIOLATION_DESCRIPTION VARCHAR(256)
);
CREATE UNIQUE INDEX pk_TABLE_VIOLATION_TYPE ON TABLE_VIOLATION_TYPE (VIOLATION_TYPE ASC);
------------------------------------------------------------------------------

--08. TABLE_DT
CREATE TABLE TABLE_DT
(
ID_DT INTEGER NOT NULL,
OKRUG VARCHAR(256),
PREF VARCHAR(256),
DISTRICT VARCHAR(256),
YARD_OWNER_NAME VARCHAR(256),
OBJECT_ADDRESS VARCHAR(512)
);
CREATE UNIQUE INDEX  pk_TABLE_DT ON TABLE_DT (ID_DT ASC);
-------------------------------------------------------------------------------

--09. TABLE_ODH
CREATE TABLE TABLE_ODH
(
ID_ODH INTEGER  NOT NULL,
OKRUG VARCHAR(256),
OBJECT_NAME VARCHAR(256),
CUSTOMER_NAME VARCHAR(256),
CONTRACTOR_NAME VARCHAR(256)
);
CREATE UNIQUE INDEX  pk_TABLE_ODH ON TABLE_ODH (ID_ODH ASC);
-------------------------------------------------------------------------------

--10. TABLE_CONTAINER_AREA
CREATE TABLE TABLE_CONTAINER_AREA
(
ID_CONTAINER_AREA INTEGER  NOT NULL,
YARD_ID INTEGER,
OBJECT_ADDRESS VARCHAR(512),
OKRUG VARCHAR(256),
DISTRICT_NAME  VARCHAR(256)
);
CREATE UNIQUE INDEX  pk_TABLE_CONTAINER_AREA ON TABLE_CONTAINER_AREA (ID_CONTAINER_AREA ASC);
-------------------------------------------------------------------------------

