BEGIN TRANSACTION;
--
DROP TABLE TABLE_VIOLATION_TYPE;
--
--07. TABLE_VIOLATION_TYPE
CREATE TABLE TABLE_VIOLATION_TYPE
(
OBJECT_TYPE VARCHAR(256) NOT NULL,
VIOLATION_TYPE VARCHAR(256) NOT NULL,
STATUS INTEGER
);
CREATE UNIQUE INDEX pk_TABLE_VIOLATION_TYPE ON TABLE_VIOLATION_TYPE (OBJECT_TYPE, VIOLATION_TYPE);

--
COMMIT TRANSACTION;
