BEGIN TRANSACTION;
INSERT INTO TABLE_OBJECT_TYPES (OBJECT_TYPE, OBJECT_TYPE_DESCRIPTION) VALUES ('ДТ','ДВОРОВАЯ ТЕРРИТОРИЯ');
INSERT INTO TABLE_OBJECT_TYPES (OBJECT_TYPE, OBJECT_TYPE_DESCRIPTION) VALUES ('КП','КОНТЕЙНЕРНАЯ ПЛОЩАДКА');
INSERT INTO TABLE_OBJECT_TYPES (OBJECT_TYPE, OBJECT_TYPE_DESCRIPTION) VALUES ('ОДХ','ОБЪЕКТ ДОРОЖНОГО ХОЗЯЙСТВА');
COMMIT TRANSACTION;