BEGIN TRANSACTION;
INSERT INTO TABLE_VIOLATION_TYPE (VIOLATION_TYPE, VIOLATION_DESCRIPTION) VALUES ('Снег у входной группы','Снег у входной группы');
INSERT INTO TABLE_VIOLATION_TYPE (VIOLATION_TYPE, VIOLATION_DESCRIPTION) VALUES ('Мусор на территории','Мусор на территории');
INSERT INTO TABLE_VIOLATION_TYPE (VIOLATION_TYPE, VIOLATION_DESCRIPTION) VALUES ('Не осуществляется полив газонов','Не осуществляется полив газонов');
COMMIT TRANSACTION;